In [3]:
import numpy as np

In [3]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
r = np.random.randint(4,90,30)
r

array([62, 60, 10, 10, 30, 19, 89, 60, 76, 51, 10, 26, 13, 11, 43, 31, 83,
       25, 70, 24, 10, 33, 58, 38, 73, 51, 78, 38,  4,  8])

In [11]:
r.shape

(30,)

In [18]:
type(r)

numpy.ndarray

In [31]:
k = r.reshape((10,3))
k

array([[62, 60, 10],
       [10, 30, 19],
       [89, 60, 76],
       [51, 10, 26],
       [13, 11, 43],
       [31, 83, 25],
       [70, 24, 10],
       [33, 58, 38],
       [73, 51, 78],
       [38,  4,  8]])

In [16]:
k.shape

(10, 3)

In [17]:
type(k)

numpy.ndarray

In [19]:
np.linspace(12,45,10)

array([12.        , 15.66666667, 19.33333333, 23.        , 26.66666667,
       30.33333333, 34.        , 37.66666667, 41.33333333, 45.        ])

In [22]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
arr = np.array([12,22,33,44,55,66,88,89,56],np.float32)
arr = arr.reshape(3,3)
print(arr)

[[12. 22. 33.]
 [44. 55. 66.]
 [88. 89. 56.]]


In [5]:
arr1 = np.array([1,2,3,4,12,22,33,44,30])
arr1 = arr1.reshape(3,3)
print(arr1)

[[ 1  2  3]
 [ 4 12 22]
 [33 44 30]]


In [6]:
np.add(arr,arr1)

array([[ 13.,  24.,  36.],
       [ 48.,  67.,  88.],
       [121., 133.,  86.]])

In [1]:
import numpy as n

In [ ]:
def r1():
    dice1 = n.random.randint(1,7)
    dice2 = n.random.randint(1,7)
    print(dice1)
    print(dice2)
a = ["yes","Yes","YES","Y","y"]
b = ["no","No","NO","N","n"]
user = input("enter yes or no:")
count = 0
while (count>=0):

        if user in a:
            print("user wants to play")
            r1()
            user = input("play again?")
        else:
            count += 1
            if count == len(a):
                print("user dont wants to play")
        
        
        

enter yes or no:yes
user wants to play
5
4
play again?Y
user wants to play
5
1
play again?YES
user wants to play
6
2
play again?y
user wants to play
1
1
play again?n
user dont wants to play


In [ ]:
a = ['yes','y','Y']
b = ['no', 'No','NO','N','n']
user = input("enter:")
while user == b:
    print ("user wants to play")

In [1]:
import numpy as n

In [3]:
a = ['Yes','yes','YES','Y','y']
b = ['No','no','NO','N','n']
user = input("enter yes or no:")
def r():
    dice1 = n.random.randint(1,6)
    dice2 = n.random.randint(1,6)
    print(dice1)
    print(dice2)
    inpt()
def inpt():
    user = input("play again:")
while user == a:
    print("user wants to play")
    r()

print("user dont wants to play")    

enter yes or no:yes
user dont wants to play


In [1]:
a = ['yes','Yes','YES','y']
b = ['No','NO','no','n']
user = input("enter")
print("no need")

enteryes
no need


In [ ]:
num = int(input("enter:"))
  
if num > 1: 
        for i in range(2, num//2):
            if (num % i) == 0: 
                print(num, "is not a prime number") 
                break
            else: 
                print(num, "is a prime number") 
else: 
    print(num, "is not a prime number") 

In [10]:
import pandas as p
import numpy as np

In [11]:
my = [1,2,3,4]
p.Series(my)

0    1
1    2
2    3
3    4
dtype: int64

In [3]:
from numpy.random import randn

In [6]:
np.random.seed(100)
d = p.DataFrame(randn(5,5),['A','B','C','D','E'],['U','V','W','X','Y'])

In [7]:
d

U         V         W         X         Y
A -1.749765  0.342680  1.153036 -0.252436  0.981321
B  0.514219  0.221180 -1.070043 -0.189496  0.255001
C -0.458027  0.435163 -0.583595  0.816847  0.672721
D -0.104411 -0.531280  1.029733 -0.438136 -1.118318
E  1.618982  1.541605 -0.251879 -0.842436  0.184519

In [16]:
d>0

U      V      W      X      Y
A   True   True   True  False   True
B  False  False   True  False   True
C   True   True  False   True  False
D   True  False  False  False  False
E  False  False   True   True  False

In [18]:
d.iloc[0]

U    1.672622
V    0.099149
W    1.397996
X   -0.271248
Y    0.613204
Name: A, dtype: float64

In [20]:
d['W']>0

A     True
B     True
C    False
D    False
E     True
Name: W, dtype: bool

In [22]:
d[d['W']>0]

U         V         W         X         Y
A  1.672622  0.099149  1.397996 -0.271248  0.613204
B -0.267317 -0.549309  0.132708 -0.476142  1.308473
E -0.212698 -0.339140  0.312170  0.565153 -0.147420

In [23]:
d[d['X']>0]

U        V         W         X        Y
C  0.195013  0.40021 -0.337632  1.256472 -0.73197
E -0.212698 -0.33914  0.312170  0.565153 -0.14742

In [24]:
d['Alt']=d['X']+d['W']

In [25]:
d

U         V         W         X         Y       Alt
A  1.672622  0.099149  1.397996 -0.271248  0.613204  1.126748
B -0.267317 -0.549309  0.132708 -0.476142  1.308473 -0.343434
C  0.195013  0.400210 -0.337632  1.256472 -0.731970  0.918840
D  0.660232 -0.350872 -0.939433 -0.489337 -0.804591 -1.428771
E -0.212698 -0.339140  0.312170  0.565153 -0.147420  0.877323

In [65]:
d.drop('Y',axis = 1,inplace=False)

U         V         W         X
A  1.672622  0.099149  1.397996 -0.271248
B -0.267317 -0.549309  0.132708 -0.476142
C  0.195013  0.400210 -0.337632  1.256472
D  0.660232 -0.350872 -0.939433 -0.489337
E -0.212698 -0.339140  0.312170  0.565153

In [61]:
d

U         V         W         X         Y
A  1.672622  0.099149  1.397996 -0.271248  0.613204
B -0.267317 -0.549309  0.132708 -0.476142  1.308473
C  0.195013  0.400210 -0.337632  1.256472 -0.731970
D  0.660232 -0.350872 -0.939433 -0.489337 -0.804591
E -0.212698 -0.339140  0.312170  0.565153 -0.147420

In [62]:
d

U         V         W         X         Y
A  1.672622  0.099149  1.397996 -0.271248  0.613204
B -0.267317 -0.549309  0.132708 -0.476142  1.308473
C  0.195013  0.400210 -0.337632  1.256472 -0.731970
D  0.660232 -0.350872 -0.939433 -0.489337 -0.804591
E -0.212698 -0.339140  0.312170  0.565153 -0.147420

In [10]:
d.drop('A',axis = 0)

U         V         W         X         Y
B  0.514219  0.221180 -1.070043 -0.189496  0.255001
C -0.458027  0.435163 -0.583595  0.816847  0.672721
D -0.104411 -0.531280  1.029733 -0.438136 -1.118318
E  1.618982  1.541605 -0.251879 -0.842436  0.184519

In [11]:
d

U         V         W         X         Y
A -1.749765  0.342680  1.153036 -0.252436  0.981321
B  0.514219  0.221180 -1.070043 -0.189496  0.255001
C -0.458027  0.435163 -0.583595  0.816847  0.672721
D -0.104411 -0.531280  1.029733 -0.438136 -1.118318
E  1.618982  1.541605 -0.251879 -0.842436  0.184519

In [20]:
d.loc[['A','B']]

U        V         W         X         Y
A -1.749765  0.34268  1.153036 -0.252436  0.981321
B  0.514219  0.22118 -1.070043 -0.189496  0.255001

In [49]:
np.random.seed(1101)
np.random.randint(1,23,9)

array([20,  1, 19, 19,  5, 15, 13,  3, 21])

In [2]:
import numpy as np
import pandas as p

In [16]:
s = int(input('enter initial value:'))
f = int(input("enter final value:"))

enter initial value:12
enter final value:40


In [25]:
for val in range(s,f+1):
    for n in range(2,val):
        if (val%n == 0):
            break
            
    else:
        print(val)
            

13
17
19
23
29
31
37


In [26]:
import numpy as n
import pandas as p

In [27]:
data={'State':['Andhra Pradesh','Andhra Pradesh','TamilNadu','TamilNadu','Karnataka','Karnataka'],'Cities':['Hyderabad','Visakhapatnam','Chennai','Coimbator','Mysore','Banglore'],'Population':[68.1,20.4,98.8,21.3,12.8,85.0]}

In [30]:
data.values()

dict_values([['Andhra Pradesh', 'Andhra Pradesh', 'TamilNadu', 'TamilNadu', 'Karnataka', 'Karnataka'], ['Hyderabad', 'Visakhapatnam', 'Chennai', 'Coimbator', 'Mysore', 'Banglore'], [68.1, 20.4, 98.8, 21.3, 12.8, 85.0]])

In [31]:
D = p.DataFrame(data)

In [32]:
D

State         Cities  Population
0  Andhra Pradesh      Hyderabad        68.1
1  Andhra Pradesh  Visakhapatnam        20.4
2       TamilNadu        Chennai        98.8
3       TamilNadu      Coimbator        21.3
4       Karnataka         Mysore        12.8
5       Karnataka       Banglore        85.0

In [44]:
grp = D.groupby('State')

In [46]:
grp

In [41]:
grp.mean()

Population
State                     
Andhra Pradesh       44.25
Karnataka            48.90
TamilNadu            60.05

In [47]:
grp.sum()

Population
State                     
Andhra Pradesh        88.5
Karnataka             97.8
TamilNadu            120.1

In [50]:
grp.std()

Population
State                     
Andhra Pradesh   33.728993
Karnataka        51.053110
TamilNadu        54.800776

In [56]:
 D.groupby('State').sum().loc['Karnataka']

Population    97.8
Name: Karnataka, dtype: float64

In [57]:
grp.sum().iloc[0]

Population    88.5
Name: Andhra Pradesh, dtype: float64